name: atrribute-graph
channels:
  - conda-forge  
  - defaults
dependencies:
  
  - python=3.12 
  
  - cdlib>=0.4.0
  - dask>=2025.11.0
  - leidenalg>=0.11.0
  - matplotlib>=3.10.6
  - networkx>=3.5
  - numpy>=2.3.3
  - pandas>=2.3.3
  - psutil>=7.1.3
  - pyclustering>=0.10.1.2
  - python-igraph>=1.0.0
  - python-louvain>=0.16
  - rich>=14.2.0
  - scikit-learn>=1.7.2
  - seaborn>=0.13.2
  - statsmodels>=0.14.5
  
  - pip
  - pip:
    - torch>=2.9.1
    - wurlitzer>=3.1.1